config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'posts#index'

  get 'about' => 'pages#about', as: :about

  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :user

    scope :most_recent, -> {order(id: :desc)}

    def created_date
      "Created: #{created_at.strftime('%-H:%-M:%-S %-b %-d, %Y')}"
    end
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_many :comments

  scope :most_recent, -> {order(id: :desc)}

  def should_generate_new_friendly_id?
    title_changed?
  end

  def display_published_date
    "Published #{created_at.strftime('%-b %-d, %Y')}"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, prepend: true
  skip_before_action :verify_authenticity_token
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: [:index, :show, :create, :destroy]

  def index
    @comments = @post.comments.most_recent
    commentArray = []
    @comments.each do |item|
      commentArray.push(
          id: item.id,
          body: item.body,
          created_at: item.created_date,
          commenter_id: item.user_id,
          commenter: User.select(:email).find(item.user_id).email
      )
    end
    render json: commentArray
  end

  def create
    @comment = current_user.comments.create(comment_params.merge(post_id: params[:post_id]))
    render json: {
        id: @comment.id,
        body: @comment.body,
        created_at: @comment.created_date,
        commenter_id: @comment.user_id,
        commenter: User.select(:email).find(@comment.user_id).email
      }
  end

  def show
      @comment = @post.comments.find(params[:id])
      render json: @comment
  end

  def destroy
      @comment = @post.comments.find(params[:id])
      @comment.destroy
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_post
    @post = Post.friendly.find(params[:post_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def about

    end

  end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.most_recent
    postArray = []
    @posts.each do |item|
      postArray.push(
          id: item.id,
          title: item.title,
          created_at: item.display_published_date,
          description: item.description
      )
    end
    respond_to do |format|
      format.html {}
      format.json {
        render json: postArray
      }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    if (@post == nil)
      raise ActionController::RoutingError.new('Not Found')
    end
    respond_to do |format|
      format.html {}
      format.json {
        render json: {
          id: @post.id,
          title: @post.title,
          body: @post.body,
          description: @post.description,
          created_at: @post.display_published_date
        }
      }
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.save
    respond_to do |format|
      format.html {}
      format.json {
        render json: {
          id: @post.id,
          created_at: @post.display_published_date
        }
      }
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id]) rescue nil
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Posts', posts_path, class: "nav-link #{yield(:blog_active)}" %>
      </li>
      <li class="nav-item">
        <%= link_to 'About', about_path, class: "nav-link #{yield(:about_active)}" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to('Logout', destroy_user_session_path, class: "nav-link", method: :delete)%>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Login', '/users/sign_in', class: "nav-link #{yield(:login_active)}" %>
        </li>
      <% end %>
    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= yield(:page_title) %> | RailsBlog </title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body data-controller="<%= controller.controller_path %>" data-action="<%= controller.action_name %>">

    <%= render 'layouts/navbar' %>
    <br>
    <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->

    <div class="container <%= controller_name %> <%= action_name %>" >
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/react/15.2.1/react.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/react/15.2.1/react-dom.min.js'></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

    <script>
       App.State = {}
   </script>

   <% if user_signed_in? %>
     <script>
         App.State.User = {
             id: <%= current_user.id %>,
             email: "<%= current_user.email %>"
         }
     </script>
    <% end %>
  </body>
</html>

app/views/pages/about.html.erb
<%= provide(:page_title, 'About') %>
<%= provide(:about_active, 'active') %>

<div id='about'></div>

app/views/posts/edit.html.erb
<%= provide(:page_title, 'Edit Post') %>
<%= provide(:blog_active, 'active') %>

<div id="edit"></div>

<script>
  var PostsEditView = {
    post: {
      id: "<%= params[:id] %>"
    }
  }
</script>

app/views/posts/index.html.erb
<%= provide(:page_title, 'All Posts') %>
<%= provide(:blog_active, 'active') %>

<div id='main'></div>

app/views/posts/new.html.erb
<%= provide(:page_title, 'New Post') %>
<%= provide(:blog_active, 'active') %>

<div id="new"></div>

app/views/posts/show.html.erb
<%= provide(:page_title, @post.title) %>
<%= provide(:blog_active, 'active')   %>

<div id='show'></div>

<script>
  var PostsShowView = {
    postId: "<%= params[:id] %>"
  }
</script>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>